# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import omnivoice_pb2 as omnivoice__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in omnivoice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OmniVoiceTTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/omnivoice.OmniVoiceTTS/Synthesize',
                request_serializer=omnivoice__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=omnivoice__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/omnivoice.OmniVoiceTTS/Health',
                request_serializer=omnivoice__pb2.HealthRequest.SerializeToString,
                response_deserializer=omnivoice__pb2.HealthResponseArray.FromString,
                _registered_method=True)
        self.SynthesizeTest = channel.unary_unary(
                '/omnivoice.OmniVoiceTTS/SynthesizeTest',
                request_serializer=omnivoice__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=omnivoice__pb2.SynthesizeTestResponse.FromString,
                _registered_method=True)
        self.Asr = channel.unary_unary(
                '/omnivoice.OmniVoiceTTS/Asr',
                request_serializer=omnivoice__pb2.AsrRequest.SerializeToString,
                response_deserializer=omnivoice__pb2.AsrResponse.FromString,
                _registered_method=True)


class OmniVoiceTTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Asr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OmniVoiceTTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=omnivoice__pb2.SynthesizeRequest.FromString,
                    response_serializer=omnivoice__pb2.SynthesizeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=omnivoice__pb2.HealthRequest.FromString,
                    response_serializer=omnivoice__pb2.HealthResponseArray.SerializeToString,
            ),
            'SynthesizeTest': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeTest,
                    request_deserializer=omnivoice__pb2.SynthesizeRequest.FromString,
                    response_serializer=omnivoice__pb2.SynthesizeTestResponse.SerializeToString,
            ),
            'Asr': grpc.unary_unary_rpc_method_handler(
                    servicer.Asr,
                    request_deserializer=omnivoice__pb2.AsrRequest.FromString,
                    response_serializer=omnivoice__pb2.AsrResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnivoice.OmniVoiceTTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omnivoice.OmniVoiceTTS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OmniVoiceTTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.OmniVoiceTTS/Synthesize',
            omnivoice__pb2.SynthesizeRequest.SerializeToString,
            omnivoice__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.OmniVoiceTTS/Health',
            omnivoice__pb2.HealthRequest.SerializeToString,
            omnivoice__pb2.HealthResponseArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.OmniVoiceTTS/SynthesizeTest',
            omnivoice__pb2.SynthesizeRequest.SerializeToString,
            omnivoice__pb2.SynthesizeTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Asr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnivoice.OmniVoiceTTS/Asr',
            omnivoice__pb2.AsrRequest.SerializeToString,
            omnivoice__pb2.AsrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
